### ISSUE TITLE
1 sided dice

### ISSUE THREAD

**Issue by vjba** [travis-g/dice-golem#16]

**Comment by vjba** [comment]
I'm able to roll a 1 sided dice. Does this have a purpose I'm not aware of?

**Comment by travis-g** [comment]
There's nothing purposeful in particular, but from the standpoint of testing the accuracy of math calculations a D1 is somewhat helpful for bot development. Since the result of rolling a D1 must always be `1`, if for some reason it's not, I know I've done something disastrously wrong and broken Dice Golem. If rolling `3d1` ever yields something besides 3, I've messed up the library and need to fix it. It's also helpful for testing the behaviors of modifiers where more random dice results would make testing complicated. `4d6k3` would be anywhere from 3 to 18, while `4d1k3` should always be 3.

**Comment by travis-g** [comment]
Hi! It's been a while but I'm hoping the above is sufficient; I'd be happy to answer more questions! Closing for now.
